### PR TITLE
Added Naman Gupta as a member

### PR DESCRIPTION
**Pull request by namangupta111**
Currently pursuing Computer Science and Engineering (1st year) from BVCOE. Would love to delve into Linux and Open Source Software. I feel BVPLUG can provide the right platform and guidance.

### CODE REVIEW

**Comment by yask123** [comment]
Please squash these 2 commits into one, with a valid commit message eg: Added <YOUR NAME> as a member.

**Comment by namangupta111** [comment]
Is this correct?
A newbie at this stuff, had to do a force push. Don't mind me.

**Comment by yask123** [comment]
Perfect! :+1:

**Comment by namangupta111** [comment]
Wohooo!

**Pull request merged**
